apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: task5
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
